### ISSUE TITLE
[Task]  Testing the Environment (NVIDIA board)

### ISSUE THREAD

**Issue by ziliolu** [SEAME-pt/Team02-PyRacer#10]
### Description

Run sample programs or benchmarks to ensure proper hardware and software configuration.
Verify GPU utilization using tools like nvidia-smi.

### Priority

High

### Story Reference

- #5

**Comment by luis-ffe** [comment]
# ✅ DONE  ✅ 

- [x] Basic use and implementations
- [x] Got acquainted with hardware set up and configuration on the Nvidea Board
- [ ] Use of Benchmarkers 👎 

### 🔒 CLOSED 🔒
