### ISSUE TITLE
[Task]   Toolchain Configuration

### ISSUE THREAD

**Issue by ziliolu** [SEAME-pt/Team02-PyRacer#6]
### Description

Toolchain Configuration
    Install necessary compilers, debuggers, and libraries (e.g., GCC, GDB, OpenCV).
    Set up cross-compilation tools for remote development from the host machine.

### Priority

High

### Story Reference

- #5

**Comment by Rui-Pedro-Pires** [comment]
Github action created to make the deploy of the executables, it will crosscompile and use scp to send the executables with ssh.
