### ISSUE TITLE
[Task] Driver and SDK Installation in the NVIDIA board

### ISSUE THREAD

**Issue by Rui-Pedro-Pires** [SEAME-pt/Team02-PyRacer#7]
### Description

Install NVIDIA drivers for GPU acceleration.
Set up the development SDK (e.g., CUDA Toolkit, TensorRT, DeepStream).

### Priority

Medium

### Story Reference

#

**Comment by luis-ffe** [comment]
# ✅ DONE  ✅ 

- [x] All the task for this have been completed 
- [x] After extensive research on these tools we came to the conclusion that the are useless according to our team objectives.
- [x] Not used.  

### 🔒 CLOSED 🔒
