### ISSUE TITLE
[Task] Network and SSH Configuration on the NVIDIA board

### ISSUE THREAD

**Issue by Rui-Pedro-Pires** [SEAME-pt/Team02-PyRacer#8]
### Description

Configure the board for network access (Wi-Fi or Ethernet).
Enable and test SSH access for remote operation. 
Note: Its also possible to use Remote desktop for remote connection (probably more useful than SSH) 

### Priority

Medium

### Story Reference

#

**Comment by mjorgecruz** [comment]
- Configuring the board was cumbersome. Installation using the sdk manager from Nvidia led to an installation directly on the board which was not intended. In this mode, the board would not recognize the SD card.
 - To solve that, we had to flash the board with the C100 version of the jetpack OS, to switch the boot proirities and then flash the actual intended version on the SD card.
 - The version of OS installed in the Jetson is jetpack4.5.
 - There is still a concern: to finalize the installation of the OS, the sd card needs to be booted on a Jetson Nano that was correctly installed.

- We were able to connect through ssh.
